### ISSUE TITLE
SSL Issue

### ISSUE THREAD

**Issue by the-human-mustachio** [stormpath/stormpath-wordpress#5]
After adding my API keys I get this error at the top of the stormpath settings section.

There was an error with Stormpath: SSL certificate problem: unable to get local issuer certificate

Any help would be great.

WP: 4.5
PHP : 5.6.16

EDIT: installed ca-bundle.crt into my wamp directory and changed this line in php ini openssl.cafile="C:/wamp64/ca-bundle.crt"

Issue seems to be resolved

**Comment by bretterer** [comment]
Hey @MattPuccio1001 
Thank you for reporting this issue. I am not 100% sure it is an error from Stormpath directly.  Our general error that we throw in the plugin prefixes the message with "There was an error with Stormpath" and I think it was being triggered even though it was not part of Stormpath.

Since you were able to resolve it with adding the bundle certificate, I am going to close this issue.

If you feel it is not resolved, please re-open.
